export default () => {
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
  console.log('Default Export');
};